### ISSUE TITLE
Download RVD external dependencies on setup.py instead of installing them manually

### ISSUE THREAD

**Issue by LanderU** [aliasrobotics/RVD#3339]
Hi Alias Robotics team!

I've found a way to install https://github.com/aliasrobotics/RVD/blob/master/setup.py#L33-L34, without cloning and installing it by hand.

Would you accept this change if I send the PR?

It would be great to have a issue template for tool features and not only for bugs/vulnerabilities, etc.

**Comment by LanderU** [comment]
Ping @unaithetutamatumatu @EndikaGu @glerapic

**Comment by vmayoral** [comment]
Same in here @unaithetutamatumatu and @glerapic.
